### ISSUE TITLE
Implement PhoSimPredictor class using ML results from #159

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#186] opened 2016-03-24 15:50 UTC
At #159, Phil says:
> The next step could be to extract the ML parts of your notebook and repackage them into a PhoSimPredictor class, which could be trained and then pickled for use before every new PhoSim run to determine which queue to use.

### Status

@sethdigel is investigating the long CPU time jobs in Run 1, by re-doing (with @TomGlanzman) them at 1-second exposure time ("Run 1sx").

### Summary of Results

The Run 1 and Run 1sx CPU times are only approximately linearly related, meaning that our ability to predict the longest CPU times is very uncertain. See this [Confluence page](https://confluence.slac.stanford.edu/pages/viewpage.action?spaceKey=LSSTDESC&title=Phosim+CPU+times+in+Twinkles+Run+1+and+Run+1sx) for more details as they appear.

<table><tr>
<td><img src="https://cloud.githubusercontent.com/assets/710903/14294263/feebbfee-fb24-11e5-9b60-c0c8ad01afb8.png" width="100%" /></td>
<td><img src="https://cloud.githubusercontent.com/assets/710903/14294286/086ff634-fb25-11e5-8607-710e313a9e0d.png" width="100%" /></td>
</tr></table>

**Comment by drphilmarshall** [comment] 2016-03-24 16:03
Yeah! Did you make this because you have started work on it, @jchiang87 - or were you thinking @sethdigel might like to take it on? Either way @TomGlanzman should advise with how to slot it into his PhoSim workflow.

**Comment by jchiang87** [comment] 2016-03-24 16:11
Actually, my motivation was to close my issue! ;-)   I am interested on working on this, after sorting out  the mysql db work.  If it looks like we are planning to do more phosim runs soon, I can bump this up in my stack, but if Seth wants to run with it, that's ok with me.

**Comment by sethdigel** [comment] 2016-03-24 16:34
Yes, I'd like to work on this.  I actually was not overwhelmed with the 0.2 dex precision that the predictor was able to achieve for estimating CPU times and I wanted to look at ways to potentially improve it.  

The two possibilities that came to mind are scaling the CPU times by the SLAC CPU factors rather than letting the algorithm effectively discover the factors by using the batch host type as one of the 'features'.  The other is providing the sky brightness as a feature.  It does not seem to be a direct input to phosim in the instance catalogs, but the Opsim database reports what it thinks the sky brightness is, and David Kirkby posted a notebook with an example of how to calculate it.  Neither of these may agree exactly with what phosim infers as the sky brightness (something else to look at) but they should correlate, of course.  I got hung up with newbie issues and distractions. 

If these approaches look like they will improve the predictor, I'll reopen #159 and post details there.

**Comment by jchiang87** [comment] 2016-03-24 16:41
Could I ask you to post any new details here instead?  There's a lot of unrelated cruft in that issue that I'd like to avoid wading through.

**Comment by TomGlanzman** [comment] 2016-03-24 16:42
@sethdigel note that the physics override file used in Run 1 had this line pertaining to sky brightness:

# Set the nominal dark sky brightness
zenith_v 21.8

**Comment by awborgland** [comment] 2016-03-24 16:54
About this @sethdigel : "The two possibilities that came to mind are scaling the CPU times by the SLAC CPU factors rather than letting the algorithm effectively discover the factors by using the batch host type as one of the 'features'. "
It's worth doing, but I would think that you get worse results. The reason is that the CPU factor is (well, at least used to be) derived from some running some standard job(s) and see how they scaled on the different machines. Our jobs may scale differently than the standard ones so the effective CPU scaling factors for us are different than the official ones. So letting the algorithm discover them should be better. But it may be that it doesn matter. It would be interesting to see, though.

**Comment by sethdigel** [comment] 2016-03-24 18:55
Thanks, @TomGlanzman.  From the phosim reference guide, my impression is that the zenith_v parameter specifies the V-band brightness of the sky at the zenith.  This is certainly related to the phase and location of the moon, which are also independently specifiable inputs to phosim, and we clearly see a strong dependence of the CPU time on moon altitude.  So I cannot say that I know what effect zenith_v has in the phosim run, but it is not representing the actual brightness of the sky in the direction of the observation.   In the Opsim output, [this wonderful table](https://confluence.lsstcorp.org/display/SIM/Summary+Table+Column+Descriptions) by Peter Yoachim, the vSkyBright quantity is the V-band brightness in the direction of the observation, taking the Moon into account.  It is this that I think may be a better predictor of the CPU time than some Random Forest combination of moonalt, moonphase, dist2moon, etc.  David Kirkby's notebook also implements a calculation of the sky brightness, with the advantage that you can specify the band of interest.

**Comment by drphilmarshall** [comment] 2016-03-24 22:02
Glad that the focus of the discussion has shifted to feature selection - we
must be doing something right! Seth, I think the PhoSimPredictor should be
able to be run on *any* csv file, as long as it contains a column marked
'CPUtime'.: then we can set the Random Forest training procedure in stone,
and move on to comparing different input datafiles against each other. You
suggest a good initial test: which is better, your current datafile, or a
single column of `vSkyBright` values?

**Comment by sethdigel** [comment] 2016-03-24 23:08
Yes, of course technically implementing the PhoSimPredictor is not the same as making it a useful predictor.  I think that we need better than 0.2 dex but I don't know (yet) how much better is realistic.  

Regarding Random Forest and the various splitting into training data sets implemented in the Hack Day notebook, I'm also planning to figure out how to set a seed so that I can get the exact same result twice for the same input features if I want to, and the ultimately implemented PhoSimPredictor also would be precisely reproducible should anyone care to.

**Comment by drphilmarshall** [comment] 2016-03-24 23:13
Sounds good - although you would hope that after all that cross-validation
the results would not vary outside the uncertainty (once we have extracted
it ;-) )

**Comment by sethdigel** [comment] 2016-03-28 07:18
Just a brief update:  vSkyBright is not a panacea, but including it as a feature certainly helps.  It has kind of an odd distribution, with most values in the range 21.2-21.5, a fairly broad tail extending down to about 19.4, and a dozen or so entries in the 17.2 range.  The latter don't correlate as well as I would have guessed with moonalt and dist2moon.  Anyway, the MSE for the tuned Random Forest algorithm in the notebook, which models log10(cputime), decreases from 0.0084 to 0.0039 when vSkyBright is included.  I'll try applying the SLAC CPU factors next.

![cpu_rf_wvskybright](https://cloud.githubusercontent.com/assets/6035835/14072958/fef1a9ec-f479-11e5-8385-22ddd44b9301.png)

**Comment by drphilmarshall** [comment] 2016-03-28 16:58
Sweet! This is looking much better :-)  Seth, can you think of a good way
of automatically estimating uncertainty on the predictions? The best I can
think of is binning the residuals in predicted CPU time and computing std
deviations.

**Comment by rbiswas4** [comment] 2016-03-28 17:04
Maybe this was shown before and I missed this, is there a place where we
can see how much the performance is improved compared to say only using the
moon specific features (altitude, distance to moon, phase)?

**Comment by sethdigel** [comment] 2016-03-28 17:42
It was not shown before.  I am not sure what the right measure of performance is.  I quoted the Mean Square Error above.  Probably what is most interesting is the uncertainty for the longest jobs, where the accuracy of the estimates is most important and the predictions currently are least accurate.  Below is the corresponding predicted vs. actual CPU time plot for the tuned Random Forest algorithm when vSkyBright is **not** provided as a feature (but "obshistid", "expmjd", "filter", "rotskypos", "altitude", "rawseeing", "airmass", "sunalt", "moonalt", "moonphase", "dist2moon", and "hostname" are).  This was calculated from the [notebook](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/examples/notebooks/Run1CPUTimes.ipynb) that @humnaawan and @tmcclintock developed on Hack Day.

![cpu_rf_novskybright](https://cloud.githubusercontent.com/assets/6035835/14084606/57f56186-f4d0-11e5-9caf-18a04772f524.png)

b, d, f, h, k stand for bullet, dole, fell, hequ, and kiso batch host classes in the SLAC farm.  Their SLAC 'CPU Factors' are listed on #159.  Anyway, vSkyBright is not in the instance catalogs input to phosim, but it is clearly telling us something that the RF algorithm was not inferring from the phosim inputs.

**Comment by rbiswas4** [comment] 2016-03-28 18:04
Very half-baked thought:

I was wondering if you have considered the use violin plots on predicted (CPU Time - CPU Time ) on the y axis and CPU Time on the x axis. Given dataframes, these can be easily made using seaborn for example:  https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.violinplot.html : Maybe this is hard with all the filters together?

**Comment by drphilmarshall** [comment] 2016-03-28 19:16
As I recall neither filter nor hostname made much difference to the
prediction precision but it'd be worth checking. I was thinking that
prediction precision could be shown with means and confidence intervals in
bins, and maybe visualized by filling in between points to make a shaded
band:
http://stackoverflow.com/questions/12957582/matplotlib-plot-yerr-xerr-as-shaded-region-rather-than-error-bars
 One could also plot a violin at each CPUtime bin center but I worry we may
not have enough points to get a good distribution shape. I think I'd want
to see (PredictedCPUTime - CPUTime)/PredictedCPUTime vs log PredictedCPUTime
with the y axis values in percent.

**Comment by rbiswas4** [comment] 2016-03-28 20:09
@sethdigel Sorry, I realize that this comment "Maybe this was shown before and I missed this, is there a place where we can see how much the performance is improved compared to say only using the
moon specific features (altitude, distance to moon, phase)?
" was off-context.

The point I was making was that it is also possible with the given data to make a prediction per band using some very basic features such as moon altitude, maybe distance to moon. Surely, the ML method using more features does better, but by how much? Can we get a sense of this increased performance in terms of, say number of predictions that differ from the true value by 5 percent of the predicted CPU time? In terms of practical scheduling this is the sort of quantity that I imagine would be useful, and from that point of view when could we say we have a good enough predictor.

Of course, practical issues of scheduling aside, this is a fun problem anyway. The more in-context point there is 
- Of course vsky_brightness should help. In fact, I would prefer the filtskybrightness. Neither of these are passed to OpSim, but presumably OpSim would calculate internally something that corresponds to these values.

**Comment by sethdigel** [comment] 2016-03-29 07:04
Thanks, @rbiswas4.  Yes, that sounds like a sensible definition of a good predictor.  

Of course, we don't have the ideal data set for making a predictor - more than 100 runs reached the 5-day CPU limit so we have only lower limits on CPU time for these (and actually they are not used in any way in this study).  And any predictor is likely to be challenged in making extrapolations.  

In the run up to Run 1 I had suggested making short-time versions of the visits, using (say) 3 s exposures instead of 30 s for the phosim.  With much shorter exposures we could figure out how much CPU time would be required for even the 'worst' visits (and taking into account phosim startup time), for developing a predictor that would better cover the parameter space.  This might be worth considering doing for the visits that hit the CPU limit.

Regarding filtskybrightness, here's a plot comparing it with vSkyBright for the Run 1 runs.  The symbol size is scaled logarithmically by CPU time, and the points are colored by filter.  I would have bet that vSkyBright would have been better correlated with CPU time, but clearly filtskybrightness is.  (So I guess that means that phosim is not wasting a lot of time generating photons out of band for the filter, or at least that out-of-band photons are faster to simulate because they do not get through the filter.)  

![filt_v_cpu](https://cloud.githubusercontent.com/assets/6035835/14100298/4ece4fde-f541-11e5-8ffd-6671e201b81f.png)

I can't say that I understand all the features of this plot.

Swapping in filtskybrightness for vSkyBright in the Random Forest analysis reduced the MSE by about 10%.  I'll look into how Humna and Tom were evaluating which parameters actually mattered in the RF results.

**Comment by rbiswas4** [comment] 2016-03-29 08:05
@sethdigel 
> So I guess that means that phosim is not wasting a lot of time generating photons out of band for the filter, or at least that out-of-band photons are faster to simulate because they do not get through the filter.

I had assumed this to be the case without too much thinking ... this is what had led me to believe that things will correlate better with filtskybrightness.  Your statement brings up the question of how phosim deals with out of band flux ? Does it outright ignore that or maybe does it to a quick numerical calculation to threshold what is important?

About the plot: My guess is that the green and reddish points at the top are for u, g, r which are are close to 'v' in terms of wavelength. So, we can assume that the spectrum is similar and therefore the sky brightnesses in these bands are approximately equal to the vsky brightness. z and y and brighter and y is always bright. 

What I find intriguing is that the z band CPU times are the most, even if the brightness is not as high as the y band. Maybe the z band is broader and it has to generate more photons to describe the spectrum shape covered by z band?

**Comment by rbiswas4** [comment] 2016-03-29 16:54
@drphilmarshall 


I had missed your post ... yes, I would agree that it is possible that we will not have enough

**Comment by sethdigel** [comment] 2016-03-31 17:27
@TomGlanzman is launching another Run 1 task in the pipeline to regenerate exactly the same visits but with 1 s exposures instead of 30 s.  With 30 s exposures, 103 of the visits had hit the 120 CPU hour limit, and it is visits like these that we'd be most interested in being able to predict accurately.  The original Run 1 task took about 4 CPU years, with 1.5 years going into visits that hit the CPU limit.  This scaled down task should go quickly.

**Comment by drphilmarshall** [comment] 2016-03-31 17:44
Sounds good - interested to see how long this takes. This should be helpful for any smoke test planning (#144) we might eventually want to do as well. We'll need a name for this PhoSim run. "Run X" is out, because a "Run" indicate both PhoSim and DM. What are you calling it, @TomGlanzman ?

**Comment by sethdigel** [comment] 2016-03-31 18:08
> What I find intriguing is that the z band CPU times are the most, even if the brightness is not as high as the y band. Maybe the z band is broader and it has to generate more photons to describe the spectrum shape covered by z band?

@rbiswas4, good question.  The z band is not especially broader in wavelength (or frequency) range than the other bands.  I had thought that the big blue dot in the plot above was a blend, and so not the longest CPU time, but I see that I mistakenly made the plot only with the ~900 runs that finished in less than about 33 hours.  Here is the complete plot for Run 1.  The points are still logarithmically scaled according to CPU time.  The z band times relative to the other bands look more understandable with the complete set of runs shown.

![filt_v_cpu](https://cloud.githubusercontent.com/assets/6035835/14185893/a5cdc71a-f730-11e5-9344-149615402cd9.png)

**Comment by rbiswas4** [comment] 2016-03-31 18:20
Actually, I was still confused as I was expecting the y band to take longer times as the filter sky brightness is much higher there than the others.

**Comment by yoachim** [comment] 2016-03-31 18:29
As a possible (partial) explanation, I'll point out that the y-band is taken entirely in twilight. The current OpSim has a crude model for the twilight sky level (it sets it to a "bright" constant when the sun gets above a certain altitude, something like -18 degrees).  That little clump in the lower left are all exposures that drifted into twilight and thus got set to "bright". 

For the other filters, the sky flux is going to be dominated by scattered moonlight, and as the sky gets brighter, the points get larger as one expects.

I suspect PhoSim doesn't include a twilight component (or it's more realistic than the OpSim one), so there's no increase in computation time for the y-band.

**Comment by TomGlanzman** [comment] 2016-04-01 21:00
A full redo of Run1, but with 1-second exposures (rather than 30 second exposures) is running and mostly complete.  The SLAC task name is Twinkles-phoSim1sx.  At this moment, about 100 (of 1227) jobs are still running.

http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?task=41492097

**Comment by drphilmarshall** [comment] 2016-04-01 21:13
Great! Run 1sx shoudl be a nice little CPU time dataset. Thanks Tom :-)

**Comment by TomGlanzman** [comment] 2016-04-01 21:18
Note to @sethdigel : the log files will look just a bit different.  Some new, mostly debugging, data was added, including a dump of the first 21 lines of the instance catalog, post modification, just before invoking phoSim.

**Comment by TomGlanzman** [comment] 2016-04-01 21:43
Here is what the execution time distribution looks like for the 1-second exposure version of Run1 (with 85 jobs still running).
![phosim1sx](https://cloud.githubusercontent.com/assets/9436484/14220921/0b24e99e-f818-11e5-9a90-8f41aba82be8.png)

**Comment by sethdigel** [comment] 2016-04-01 22:38
Thanks a lot, @TomGlanzman.  That distribution is interesting.  I'd say that it suggests that the overhead in starting up phosim is a small fraction of the execution time.  On the other hand, looking at the CPU times in the summary plots (and accounting for the 30-s runs that never finished), the speed up looks like about a factor of only 20.  Also, thanks for the heads up about the change in the log files.

**Comment by sethdigel** [comment] 2016-04-04 07:25
I've posted some plots comparing the Run 1 and Run 1sx results [here](https://confluence.slac.stanford.edu/display/LSSTDESC/Phosim+CPU+times+in+Twinkles+Run+1+and+Run+1sx) in Confluence.  I expect to have more to post soon.  You can Watch that page if you want notifications.  

The CPU time ratio between the 1 s and 30 s runs has more scatter than I would have expected.  If this means that the CPU time for a phosim run for a given instance catalog is somehow not deterministic, then the accuracy of a CPU time predictor will have a floor.

Surprisingly, seven of the 1227 Run 1sx visits are still running - not sure why.

**Comment by TomGlanzman** [comment] 2016-04-04 15:30
As of Monday morning there are eight 'stuck' batch jobs.  This does not appear to be related to any sort of failure within phoSim.  The jobs are being investigated and, at some point, they will be killed and resubmitted.  Stay tuned.

**Comment by rbiswas4** [comment] 2016-04-04 15:57
@sethdigel 
I would have had similar expectations and this think this means that we should try to understand the steps that phosim goes through. Hopefully the main program will be sufficient for this. 

@TomGlanzman 
I recall that at SLAC we all had a discussion about running a very fast version (small exposure time) of the job through phosim as preparation and check that there is nothing that would crash the job ... at that time I had expected the prep job to be couple of mins. Is the 1 second run the implementation of this idea? This would say about ~93 percent of these fast jobs are done in <~ 10 minutes, but the rest take considerable time, and cannot be used as a 'prep job' .

Would be interesting to see the 87 or 100 jobs in the 1 second exposure that took 'too long' and ask what happened to these jobs in Run1 (full 30 second exposure)? What if we try too long as say 1 hour?

Also I could not make out from the plot, did any of the jobs that hit the 5 day limit in Run1 finish with the 1 sec exposure?

**Comment by sethdigel** [comment] 2016-04-04 19:19
@rbiswas4, yes, I'm afraid so.  Even a sanity check re-running the same visit a few times would be interesting.  Tom pointed out that it would be possible to add some logging in phosim.py to track how the CPU time is used in the main steps the execution, which I guess is what you also were suggesting above.  In any case, I presume that we are seeing a feature and not a bug, and the point is to figure out how much time phosim will take to run before we run it.

For the 1 s exposure visits the minimum CPU times were about 18 minutes.  The median was about 65 minutes.

I am not sure that I understand your question about the 1 s exposures that took too long.  There are a few standouts but not a well-defined set.  Just for the record, of the 103 Run 1 visits that hit the run time limit, 102 have finished.  (The remaining one is one of the stuck batch jobs that Tom mentioned.)  In their 1 s versions these visits took between 79 and 2213 CPU minutes, with a median of 671 minutes.  Very roughly speaking (for now) the median time scales to about 200 CPU hours for a 30 s visit.  The visits that hit the run limit are in the vertical feature at the right in the 3rd plot on the [Confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/Phosim+CPU+times+in+Twinkles+Run+1+and+Run+1sx).

I'd like to try to move this discussion to that page.  This Twinkles issue is nominally for implementing a CPU time estimator.  Also Confluence has better features for commenting on pages, and people who do not want to follow the particular discussion will not get spammed if they do not want to.

**Comment by drphilmarshall** [comment] 2016-04-05 16:42
Interesting, thanks @sethdigel! Do you think it's worth using your linear extrapolations from Run 1sx to train the Predictor to estimate the CPU time of the longest jobs? I know the scatter is high, but it'd at least allow us to say *something* quantitative about those runs, and perhaps trace where the longest CPU times are coming from. I agree that re-executing the longest jobs is a good idea, to get a better handle on how uncertain the predictions are at that end...


I'm trying to think more about how to keep track of this kind of investigative work. The confluence page you made is a summary of results, with half a dozen plots with accompanying notes. This sort of page is what IPython notebooks are very good for, so if the analysis is being done in python I think I'd recommend that format. One problem though is that the notebooks can get quite large, so are not always best checked in because they can drag down the whole repo. You can also make confluence-like pages in markdown, either in a subfolder of `doc`, or on the [wiki](https://github.com/DarkEnergyScienceCollaboration/Twinkles/wiki): these don't have comments underneath them, but this may not be a problem: the conversation about the work is happening here, in the issue thread, so it makes sense to keep it here. You can also just make long posts in issue threads and pull requests that show multiple plots, and you can edit them afterwards too - but I guess these can become somewhat hidden when they get closed/merged. Maybe that's a good thing? I'm not sure what the right answer is, but confluence has a serious downside which is that it is behind the DESC firewall, and so invisible to casual non-member visitors from eg the DM group.

Regarding "spam", did you know you can unsubscribe from any single issue vis this button in the right hand sidebar: 
![image](https://cloud.githubusercontent.com/assets/710903/14289403/843d3b70-fb0f-11e5-83a0-7973e9001870.png)
You can also "unwatch" the repository, so that you only get notifications when you are mentioned, or if you reply to the conversation. This is the default confluence behavior, I think.

**Comment by drphilmarshall** [comment] 2016-04-05 16:58
PS. I just tried checking in an IPython notebook to the Twinkles wiki (which is itself a git repository). [It does not render correctly](https://github.com/DarkEnergyScienceCollaboration/Twinkles/wiki/Test.ipynb) and also does not appear in the [wiki's page list](https://github.com/DarkEnergyScienceCollaboration/Twinkles/wiki). (It looks as though only `*.md` files are picked up and displayed in the right hand sidebar.)

**Comment by sethdigel** [comment] 2016-04-05 18:32
@drphilmarshall, yes the 1sx simulations provide *some* information about CPU times for the longest Run 1 jobs, although as we've seen the approximations/optimizations in phosim prevent (for the better) the CPU times from scaling linearly with the simulated exposure time.  I don't want to head down another ML path developing a predictor for the CPU times for the long runs based on the 1sx results (to then plug in with the Run 1 CPU times as input to the Random Forest training).  But I'll try making the linear fits of Run 1 vs. Run 1sx CPU times separately for ranges of filtSkyBrightness and/or filter band. 

@TomGlanzman kindly re-ran a selection of the 1sx visits yesterday, as documented in the [Confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/Phosim+CPU+times+in+Twinkles+Run+1+and+Run+1sx).  For the visits that ran on the same batch host class as before, the CPU times were consistent, within 5% worst case.  For the visits that ran on different host classes, we now can infer empirical 'CPU factors' for relative performance on phosim runs (which are different from the CPU factors defined by the SLAC computing center).

I see the advantage of Confluence as enabling curated (if that is the right term) pages for an investigation.  The linear format of what is nominally an issue-tracking thread in Github does not work well for that.  I've been a Confluence user for much longer than I've used Github, but I think that I can be objective.  If I want people to compare a plot that I just made with one that I posted last week, I can place them side by side in Confluence.  On this issue thread, the first plot would be way up there somewhere, unless I post it again, of course.  Also, Confluence is a DESC resource.  I hadn't thought about our friends in DM or in the wider world out there, but if access to Confluence by non-DESC people is an issue for DESC-related work, I think there are various ways that could be accommodated in Confluence.

**Comment by drphilmarshall** [comment] 2016-04-05 19:08
@sethdigel As a test, I just re-implemented part of the Confluence page in the [first comment on this thread](https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/186#issue-143283731), just to see what it would be like, trying to use issue threads as online lab-books. The 2-panel image display was a bit fiddly, but the copy and paste image uploading is nice, as is the previewing. Note that the images get stored in the GitHub rawusercontent store, which is different to what Confluence does. I guess the argument could be that if we really valued the plots, we'd check them in to the repo (or its wiki) somewhere.

**Comment by rbiswas4** [comment] 2016-04-05 22:26
@sethdigel 
> I am not sure that I understand your question about the 1 s exposures that took too long. There are a few standouts but not a well-defined set. 

Yes, Sorry. I misread the minutes in @TomGlanzman's histogram for seconds, so when I thought that a large fraction of jobs had finished in  < 10 minutes, I should have been thinking less than 10 hours! So, as a way of preparing to make sure there was nothing in the job that would crash it when run with the full exposure time, this is probably too expensive. 

I am sure this is already there, but can you please point me to  a list of obsHistIDs in say a cvs file for the 103 jobs that hit the queue limit in run1 ? Thanks!

@drphilmarshall 
On notebooks, on the File menu, there is a tab that allows you to download the notebook into different formats, including html or md . When I have done this, it downloads markdown files with png files which are automatically linked. This could be used to render the ipython notebooks in github pages/ docs/ wiki or maybe even confluence (maybe html works?). Without having really done it, I have a feeling it might be best to either use docs with markdown/reST embedding code/figs as needed and link from a project page on github. If available, an even better option might be to try to use @jonathansick 's technology being used for technotes using restructured text: that can accomodate usual markdown, code blocks, figures, latex math.

**Comment by sethdigel** [comment] 2016-04-05 23:17
@rbiswas4, this file http://www.slac.stanford.edu/~digel/lsst/run1_metadata_v5.csv has information for all of the Run 1 visits.  The value in the column 'runlimit' is 1 for the phosim runs that hit the CPU time limit.  For these runs the entries in the 'cputime' column show the CPU time used up to the when the jobs got killed by the batch system.  (This file also has columns with vSkyBright and filtSkyBrightness as calculated by OpSim.)  If you like, I could post a version that has just the runlimit = 1 entries, or find a place for it in the Twinkles repository, possibly forestalling another visit from @drphilmarshall.

**Comment by rbiswas4** [comment] 2016-04-06 01:23
@sethdigel . Got it! and having a seperate file with runlimit =1 is probably not very useful, more files -> more confusion . 

I have not put any real thought into this, more thinking aloud: Our thinking has been that phosim runs that hit limit are due to sky background. What if we are wrong and somehow, there is some superbright source that is creeping into the image? But we cannot even look at the image since these runs died. What if we try to repeat them with sky background tuned off? That should be relatively fast.

**Comment by TomGlanzman** [comment] 2016-04-06 01:35
@rbiswas4 it would seem that the 1 sec exposure visits corresponding to the 30 sec timed out runs might have some clues as to the presence of extremely bright sources?  Or directly from the instance catalogs?

**Comment by rbiswas4** [comment] 2016-04-06 01:57
@TomGlanzman That is correct though. But to get that from the exposures the same way we are trying to calculate the sky noise, it would require the 1 second run to go through the DM processing.  That is a possible route we should explore. 

Instance catalogs, yes, it should be possible, but it is not clear what makes a source too bright etc. yet to me.

**Comment by sethdigel** [comment] 2016-04-18 22:16
Back on the topic of the PhoSimPredictor class, using the Run 1sx results to estimate CPU times for the Run 1 visits that reached the CPU time limit, and scaling the CPU times by empirical factors to make equivalent times for the fell-class of batch hosts, the tuned Random Forest predictor looks pretty good (MSE ~ 0.005) with only three features used to train it (moonalt, filter, and moonphase, in decreasing order of importance).  The next most important feature is filtskybrightness (which is not in the instance catalogs for phosim but needs to be looked up from the Opsim run or calculated).  Including it could reduce the MSE to ~ 0.004, which does not seem worth the gain.

With three features, the pickle file for the tuned Random Forest object is 17 Mbyte.  I'm new at this, but that seems a lot larger than I would have guessed.  Is there any sensitivity about putting something that large into the Twinkles repository?  If not (or if so), where should it go?  Where should the PhoSimPredictor class go (twinkles/python/desc/twinkles)?

**Comment by drphilmarshall** [comment] 2016-04-19 14:25
Great stuff, Seth! Pleased the Run 1sx data helped out. If I were you I
wouldn't worry too much about economizing on features: the ML philosophy is
"do whatever it takes to minimize MSE", so unless using 4+ features is
expensive in some way, just throw them in and get a better prediction. The
pickle files should only be stored locally, for example wherever the
workflow engine needs to be able to pick them up - @TomGlanzman will figure
that out, I guess. The only things to be checked in are the code, and any
docs or notebooks that explain it.

**Comment by sethdigel** [comment] 2016-04-19 22:44
I had been scared by how quickly the size of the pickle file scaled with the number of features.  Adding the three next-most important features increased the size by a factor of four, to 64 Mbyte, for what seemed like diminishing (although measurable) returns.  

Anyway, the number of features included can be tweaked later.  Depending on how the predictor is actually used (e.g., if we'd like to run it through all of the instance catalogs before the pipeline processing is launched) it might make sense to just generate the random forest on the fly at the start of the script and not bother pickling it.

**Comment by drphilmarshall** [comment] 2016-04-20 03:58
Yes, this sounds like a good plan. Also a 64Mb local pickle is no problem
to make, store and unpack.

**Comment by sethdigel** [comment] 2016-05-04 08:07
I've made a branch called issue/186/cpu_time_predictor and pushed three files:
data/run1_metadata_v6.csv, which has the complete metadata for the Run 1 phosim visits, including CPU times scaled to their equivalents on 'fell' batch hosts, and estimated CPU times from Run 1sx (1-s visits) for the 103 Run 1 visits that reached the 120 hr CPU limit.

python/desc/twinkles/run1_cpu_generate_rf.py, which generates a Random Forest predictor based on the moonalt, moonphase, and filter metadata.  The predictor is saved as a pickle file (34 Mbyte for 3 features).  A fixed seed is specified in the code, so the same RF is generated each time.  For the particular seed I picked (999) th MSE (in log10 CPU time) is 0.0047.

python/desc/twinkles/phosim_cpu_pred.py, which implements a class, possibly stupid and inefficient, that applies the RF predictor to estimate CPU times for 30-s phosim visits based on user-specified moonalt, moonphase, and filter.  Alternatively, an obsHistID from the kracken_1042 Opsim run can be specified and the metadata will be looked up in the corresponding sqlite database.  (Right now the code is hardwired to look for the database in a certain directory on SLAC Linux.)  The code has a couple of simple examples, including one that generates predicted fell CPU times for each of the Run 1 visits and compares them with the actual times:

![predicted_vs_actual](https://cloud.githubusercontent.com/assets/6035835/15008287/14373d62-1194-11e6-8c5a-ad72e4de2d1d.png)

**Comment by drphilmarshall** [comment] 2016-09-21 22:52
Hi @sethdigel - revisiting this issue from May 4. Is the code in your `issue/186/cpu_time_predictor` ready for @TomGlanzman to use when setting up Tun 3 PhoSim jobs? If so, you could submit a pull request from that branch to`master` and assign it to Tom for code review. Tom could then merge it in when he was happy. Sound like a plan? Hopefully one of your commits will close this issue! :-)

**Comment by sethdigel** [comment] 2016-09-21 23:29
The code in issue 186 was [merged into master](https://github.com/DarkEnergyScienceCollaboration/Twinkles/pull/240) on July 26.  I haven't deleted the branch but I suppose that I could.  I'll go ahead with closing this issue.

Based on Tom's experience with PhoSim-deep-pre3 runs, which are all for the same visit but simulate an entire focal plane, I am belatedly appreciating the important influence of bright stars.  I have a posting at #315 about this.  As it is, the cpu_time_predictor should be useful to estimate a CPU time floor but the brightest few stars in a typical LSST field of view have a large effect, over a fairly large region of the focal plane.

**Closed by sethdigel** 2016-09-21 23:29 UTC
Labels: PhoSim

**Comment by drphilmarshall** [comment] 2016-09-21 23:55
Thanks Seth. I guess the next upgrade to the PhoSim predictor could be to
tell it about the bright stars in the instance catalog, then! We should
have some good data to train and test on when DC1 PhoSim Deep has been run.

**Comment by jchiang87** [comment] 2016-09-22 00:04
Tom is currently running two different visits, [921297](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/si.jsp?stream=41883210) and [1668469](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/si.jsp?stream=41878856), so there are two different observing conditions available.  The original plan for my PhoSim Deep tests was to have five different visits of the same field to exercise the full focal plane coadd code from the Stack.  Since the first two never finished, I settled for five visits just simulating the central raft, which were sufficient for my tests.
