### ISSUE TITLE
Install w.2016.20 weekly at NERSC

### ISSUE THREAD

**Issue by heather999** [DarkEnergyScienceCollaboration/Twinkles#242] opened 2016-05-13 03:40 UTC
The installation was going along very well, I was running "rebuild -r w.2016.20 lsst_apps" and then it hit afwdata.. there must be an easy fix.. it just can't find the code for some reason.  I recall that the lsstsw doc mentioned possibly maintaining an afwdata install outside the installation area.  What version of afwdata should we grab @SimonKrughoff @jchiang87 ?

    afwdata: Traceback (most recent call last):                        
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/bin/lsst-build", line 51, in <module>                                                     
    args.func(args)                                                               
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 758, in run                                              
    manifest = p.construct(args.products)                                         
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 721, in construct
    self._add_product_tree(products, name)
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 709, in _add_product_tree
    dependencies.append(self._add_product_tree(products, dprod.name))
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 709, in _add_product_tree
    dependencies.append(self._add_product_tree(products, dprod.name))
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 709, in _add_product_tree
    dependencies.append(self._add_product_tree(products, dprod.name))
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 692, in _add_product_tree
    ref, sha1 = self.product_fetcher.fetch(productName)
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 305, in fetch
    raise Exception("Failed to clone product '%s' from any of the offered repositories" % product)
    Exception: Failed to clone product 'afwdata' from any of the offered repositories

**Comment by tony-johnson** [comment] 2016-05-13 15:31
Hi Heather, not directly relevant, but I tried following Simon's instructions on my ubuntu laptop just to see what would happen. It got a good way though and then failed with: 

*** error building product mariadbclient.

I am wondering if this is the same error you saw before when building for NERSC? When I look in the log file I see:

:::::  [2016-05-13T01:06:39.408611Z] Setting up environment with EUPS
:::::  [2016-05-13T01:06:39.480713Z] + eupspkg PRODUCT=mariadbclient VERSION=10.1.11.lsst2 FLAVOR=generic config
:::::  [2016-05-13T01:06:39.598864Z] grep: /etc/redhat-release: No such file or directory

Of course I do not have an /etc/redhat-release, and neither does NERSC. Anyone have any experience of building this on non-REDHAT machines, is it even supported?

**Comment by SimonKrughoff** [comment] 2016-05-13 16:24
@heather999 very strange.  It seems like your lsstsw is not up to date.  Did you do a `git pull` before you started the build?  That repo also requires git-lfs, but that should have come with the git installed by lsstsw.

@tony-johnson that could be a red herring.  If you don't have cmake installed, mariadbclient will fail.  I'll ask around for others building on ubuntu.

**Comment by tony-johnson** [comment] 2016-05-13 16:46
Hi Simon, after installing cmake and libncurses5-dev I got past the mariadb build.  It took a few more package installs to get doxygen to build, but I am making progress.

**Comment by cwwalter** [comment] 2016-05-13 16:59
BTW just as a note.. I was surprised to learn that conda supplies cmake.  It isn't in the default packages but you can do a 'conda install cmake' if you need it.

**Comment by heather999** [comment] 2016-05-13 17:49
@SimonKrughoff I'm using a fresh clone of lsstsw, but I also did a git pull.  I'll try it again to confirm.
 
@tony-johnson That wasn't the same issue I had with mariadb - I can look it up, but it was a missing system library associated with the mariadb server, as I recall.  cmake was available in that failed attempt at NERSC.  Meanwhile, this latest attempt got past mariadbclient just fine, so I have high hopes that all will be fine once I get beyond this afwdata issue.

**Comment by SimonKrughoff** [comment] 2016-05-13 18:31
@heather999 Did you say `git lfs init` before you started your build?  That may be it.  If you want, we are chatting on HipChat if you want to jump on.

**Comment by heather999** [comment] 2016-05-13 19:04
@SimonKrughoff ah.. no I had not done that, or set up ~/.gitconfig or ~/.git-credentials as outlined [here](http://developer.lsst.io/en/latest/tools/git_lfs.html)
However when I do git lfs init, that is not a recognized command.. perhaps my set up of the git config files will be enough?  I'll give it a whirl.

    heatherk@cori09:/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw> source bin/setup.sh
    notice: lsstsw tools have been set up.
    heatherk@cori09:/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw> git lfs init
    git: 'lfs' is not a git command. See 'git --help'.

    Did you mean this?
        log
    heatherk@cori09:/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw> which git
    /project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lfs/bin/git

**Comment by heather999** [comment] 2016-05-13 19:31
Unfortunately @SimonKrughoff  just updating ~/.gitconfig and creating a ~/.git-credentials didn't fix this issue (appending the same afwdata error at the end).  I followed the directions for Option 1 (anonymous access) I wonder if I'm one of the few to choose that option.. rather than Option 2 with authenticated access.  I'm looking at: http://developer.lsst.io/en/latest/tools/git_lfs.html

    heatherk@cori09:/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw> git config -l
    credential.https://lsst-sqre-prod-git-lfs.s3-us-west-2.amazonaws.com.helper=store
    credential.https://s3.lsst.codes.helper=store
    credential.https://git-lfs.lsst.codes.helper=store
    core.repositoryformatversion=0
    core.filemode=true
    core.bare=false
    core.logallrefupdates=true
    remote.origin.url=https://github.com/lsst/lsstsw
    remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
    branch.master.remote=origin
    branch.master.merge=refs/heads/master
    push.default=current

    heatherk@cori09:~> more ~/.git-credentials
    https://:@lsst-sqre-prod-git-lfs.s3-us-west-2.amazonaws.com
    https://:@s3.lsst.codes
    https://:@git-lfs.lsst.codes

    heatherk@cori09:/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw> rebuild -r w.2016.20 lsst_apps                                                               
    lsst_apps:  ok (1.2 sec).                                              
    meas_deblender:  ok (5.1 sec).                                              
    afw:  ok (11.4 sec).                                             
    daf_base:  ok (1.9 sec).                                              
    utils:  ok (1.5 sec).                                              
    base:  ok (2.0 sec).                                              
    boost:  ok (14.5 sec).                                             
    python:  ok (1.0 sec).                                              
    sconsUtils:  ok (1.9 sec).                                              
    scons:  ok (2.5 sec).                                              
    doxygen:  ok (4.0 sec).                                              
    swig:  ok (5.5 sec).                                              
    pex_exceptions:  ok (1.5 sec).                                              
    numpy:  ok (0.8 sec).                                              
    python_psutil:  ok (1.5 sec).                                              
    daf_persistence:  ok (5.9 sec).                                              
    mariadbclient:  ok (13.5 sec).                                             
    pex_logging:  ok (1.7 sec).                                              
    pex_policy:  ok (2.2 sec).                                              
    pyfits:  ok (2.4 sec).                                              
    python_d2to1:  ok (1.0 sec).                                              
    stsci_distutils:  ok (1.0 sec).                                              
    pyyaml:  ok (1.5 sec).                                              
    pex_config:  ok (2.0 sec).                                              
    ndarray:  ok (1.8 sec).                                              
    eigen:  ok (3.7 sec).                                              
    fftw:  ok (5.5 sec).                                              
    cfitsio:  ok (12.9 sec).                                             
    wcslib:  ok (3.7 sec).                                              
    minuit2:  ok (2.0 sec).                                              
    gsl:  ok (3.0 sec).                                              
    matplotlib:  ok (0.8 sec).                                              
    afwdata: Traceback (most recent call last):                          
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/bin/lsst-build", line 51, in <module>                                                     
    args.func(args)                                                               
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 758, in run                                              
    manifest = p.construct(args.products)                                         
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 721, in construct
    self._add_product_tree(products, name)
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 709, in _add_product_tree
    dependencies.append(self._add_product_tree(products, dprod.name))
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 709, in _add_product_tree
    dependencies.append(self._add_product_tree(products, dprod.name))
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 709, in _add_product_tree
    dependencies.append(self._add_product_tree(products, dprod.name))
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 692, in _add_product_tree
    ref, sha1 = self.product_fetcher.fetch(productName)
    File "/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lsst_build/python/lsst/ci/prepare.py", line 305, in fetch
    raise Exception("Failed to clone product '%s' from any of the offered repositories" % product)
    Exception: Failed to clone product 'afwdata' from any of the offered repositories
 
I assume @tony-johnson you haven't had any similar problem?

**Comment by SimonKrughoff** [comment] 2016-05-13 21:32
@heather999 did you run `git lfs install`?  It sounded before like you didn't have git-lfs installed for some reason.  What does `which git` tell you?

**Comment by heather999** [comment] 2016-05-13 22:54
@SimonKrughoff I think we're suffering from trying to have this conversation via 2 mediums.. above you had mentioned "git lfs init" and I see on HipChat it was "git lfs install" :)

Let me back up a little.. here is what I am doing step by step:

I load and unload a few modules on NERSC so that gcc 4.9.3 is available (I can show the details if it becomes interesting), then:
    git clone https://github.com/lsst/lsstsw
I update lsstsw/bin/deploy so that --cacert is used for the curl commands for eups and git
   ./bin/deploy
I believe "deploy" does the git lfs install.. but perhaps I am incorrect. Then I do:
    source ./bin/setup.sh
    rebuild -r w.2016.20 lsst_apps
and the build terminates when it is unable to find/download afwdata.

Here is the result of "which git" after "source ./bin/setup.sh"
    heatherk@cori09:/project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw> which git
    /project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/lfs/bin/git

So I think I'm using the git lsstsw provides..  now I may not have git lfs setup correctly..

**Comment by heather999** [comment] 2016-05-14 05:09
This has been a hoot-and-a-half :)  We've since discovered that the version of git-lfs (1.0.2) installed by lsstsw/bin/deploy is old and does not correspond to the configuration instructions provided in:
http://developer.lsst.io/en/latest/tools/git_lfs.html
Once I upgraded to the latest release (1.2.0), afwdata downloaded just fine.
However it is not yet a happy ending, the build ultimately failed on mariadb (similar to how it failed the last time I tried to install from source). The error is below.  I will follow-up on community.lsst.org to see if I can get some guidance.  Meanwhile, @danielsf, would it be possible to pursue making a conda install available for w.2016.20 for both lsst_apps and lsst_sims?

    mariadbclient: 10.1.11.lsst2 .....................................ERROR (101 sec).
    *** error building product mariadbclient.
    *** exit code = 1
    *** log is in /project/projectdirs/lsst/lsstDM/Cori/temp/lsstsw/build/mariadbclient/_build.log
    *** last few lines:
    :::::  [2016-05-14T04:40:25.506485Z] -- Looking for sd_notify
    :::::  [mariadbclient: 10.1.11.lsst2 .....................................ERROR (101 sec).
    *** error building product mariadbclient.
    *** exit code = 1
    *** log is in /project/projectdirs/lsst/lsstDM/Cori/temp/lsstsw/build/mariadbclient/_build.log
    *** last few lines:
    :::::  [2016-05-14T04:40:25.506485Z] -- Looking for sd_notify
    :::::  [2016-05-14T04:40:25.796143Z] -- Looking for sd_notify - not found
    :::::  [2016-05-14T04:40:25.796790Z] -- Looking for sd_notifyf
    :::::  [2016-05-14T04:40:26.020048Z] -- Looking for sd_notifyf - not found
    :::::  [2016-05-14T04:40:26.020596Z] -- Systemd features not enabled
    :::::  [2016-05-14T04:40:26.023387Z] -- Performing Test HAVE_C__Wvla
    :::::  [2016-05-14T04:40:26.382371Z] -- Performing Test HAVE_C__Wvla - Success
    :::::  [2016-05-14T04:40:29.078157Z] -- Configuring incomplete, errors occurred!
    :::::  [2016-05-14T04:40:29.078229Z] See also "/project/projectdirs/lsst/lsstDM/Cori/temp/lsstsw/build/mariadbclient/CMakeFiles/CMakeOutput.log".2016-05-14T04:40:25.796143Z] -- Looking for sd_notify - not found
    :mariadbclient: 10.1.11.lsst2 .....................................ERROR (101 sec).
    *** error building product mariadbclient.
    *** exit code = 1
    *** log is in /project/projectdirs/lsst/lsstDM/Cori/temp/lsstsw/build/mariadbclient/_build.log
    *** last few lines:
    :::::  [2016-05-14T04:40:25.506485Z] -- Looking for sd_notify
    :::::  [2016-05-14T04:40:25.796143Z] -- Looking for sd_notify - not found
    :::::  [2016-05-14T04:40:25.796790Z] -- Looking for sd_notifyf
    :::::  [2016-05-14T04:40:26.020048Z] -- Looking for sd_notifyf - not found
    :::::  [2016-05-14T04:40:26.020596Z] -- Systemd features not enabled
    :::::  [2016-05-14T04:40:26.023387Z] -- Performing Test HAVE_C__Wvla
    :::::  [2016-05-14T04:40:26.382371Z] -- Performing Test HAVE_C__Wvla - Success
    :::::  [2016-05-14T04:40:29.078157Z] -- Configuring incomplete, errors occurred!
    :::::  [2016-05-14T04:40:29.078229Z] See also "/project/projectdirs/lsst/lsstDM/Cori/temp/lsstsw/build/mariadbclient/CMakeFiles/CMakeOutput.log".::::  [2016-05-14T04:40:25.796790Z] -- Looking for sd_notifyf
    :::::  [2016-05-14T04:40:26.020048Z] -- Looking for sd_notifyf - not found
    :::::  [2016-05-14T04:40:26.020596Z] -- Systemd features not enabled
    :::::  [2016-05-14T04:40:26.023387Z] -- Performing Test HAVE_C__Wvla
    :::::  [2016-05-14T04:40:26.382371Z] -- Performing Test HAVE_C__Wvla - Success
    :::::  [2016-05-14T04:40:29.078157Z] -- Configuring incomplete, errors occurred!
    :::::  [2016-05-14T04:40:29.078229Z] See also "/project/projectdirs/lsst/lsstDM/Cori/temp/lsstsw/build/mariadbclient/CMakeFiles/CMakeOutput.log".

**Comment by heather999** [comment] 2016-05-17 21:24
We seem to have a complete build now available on Cori after some discussion
[https://community.lsst.org/t/trouble-installing-dmstack-w-2016-20-at-nersc/779](url)
I've also tested it against lsst_dm_stack_demo via:
`setup -t b2055 obs_sds`
 `./bin/demo.sh` 
The build is here: /project/projectdirs/lsst/lsstDM/Cori/w.2016.20
to use it.. I would first setup the necessary NERSC  modules:
`source /project/projectdirs/lsst/lsstDM/Cori/w.2016.20/loadmodules_w.2016.20.sh`
then
`source /project/projectdirs/lsst/lsstDM/Cori/w.2016.20/lsstsw/bin/setup.sh`
@tony-johnson @jchiang87 what shall we do now? :)

**Comment by tony-johnson** [comment] 2016-05-17 21:30
Excellent! I will try rerunning some of the run 1.1 jobs by hand to see if they work!

**Comment by SimonKrughoff** [comment] 2016-05-17 21:36
@heather999 That is really good work!  Sorry for not being more involved.  This is important information you've provided.

**Comment by jchiang87** [comment] 2016-05-17 21:39
@heather999 Could you also install a few other items?  The ones I see a need for right now are `ipython`, `nose`, `coverage`, and `iminuit` .  The last one is needed to fit light curves with `sncosmo` (which seems to be part of the Stack or sims, but somehow doesn't also pull in `iminuit`).  All of those are available via `pip install`.   We should work on a standard list of add-ons to include with each Stack/sims installation.

**Comment by heather999** [comment] 2016-05-17 21:44
You were vital in this @SimonKrughoff! I can't expect any one person to address all the questions I come up with - some of which are really just ignorance about how the builds work. It forced me to learn a few things. I think this also proves that the various communication tools are working!

@jchiang87 ok, yes I can do that.  No specific versions, just whatever pip feels like grabbing?  :)  It would be nice to have a list and to start managing the things we add-on.  I need to script the installation procedure..

**Comment by jchiang87** [comment] 2016-05-17 21:47
yes whatever pip feels like grabbing.   I haven't run into any cases for these where the default didn't work.

**Comment by heather999** [comment] 2016-05-17 22:01
Done @jchiang87 
nose 1.3.7
coverage 4.0.3
iminuit 1.2
ipython 4.2.0

**Comment by tony-johnson** [comment] 2016-05-17 22:37
When I tried running at NERSC I got:

/global/homes/t/tony_j/projects/trial/serialIngest: line 8: ingestImages.py: command not found\

My guess is that we also need:

 rebuild -r w.2016.20 pipe_tasks

@SimonKrughoff -- does this sound right, and are there other things which might be missing?

**Comment by jchiang87** [comment] 2016-05-17 22:42
The image ingest task for obs_lsstSim was renamed.  It's `ingestSimImages.py` now.

**Comment by tony-johnson** [comment] 2016-05-17 22:58
You are right, plus I forgot the 

setup lsst_apps -t b2055

**Comment by SimonKrughoff** [comment] 2016-05-17 23:00
@tony-johnson sorry for the rename.  It is on my plate to updated the cookbook.

**Comment by tony-johnson** [comment] 2016-05-19 00:04
I have been able to run several jobs using this version of the code, and so far have not seen any problems caused by the installation. I would suggest we can close this issue.

**Closed** 2016-05-19 13:43 UTC
Labels: Documentation, NERSC
