### ISSUE TITLE
Twinkles DESC request to Project

### ISSUE THREAD

**Issue by wmwv** [DarkEnergyScienceCollaboration/Twinkles#190] opened 2016-03-24 19:27 UTC
The Twinkles TaskForce would like to request the following things from LSST Project.  This request cover, and often span, both DM + SIMS.

1. SIMS master should build against DM master
2. Weekly builds should be tagged for both SIMS and DM.
3. Weekly Conda binaries based on those tags should be distributed for both SIMS and DM.
4. Breakage of SIMS against last week's DM tag or breakage of DM against last week's SIMS tag should be noted.
5. obs_lsstSim should be _prima facie_ usable for the most recent weekly tags (The fact that `processEimage.py` fails immediately with a config error for `b2006` means that it fails that _prima facie_ test.)

**Comment by wmwv** [comment] 2016-03-24 19:28
@drphilmarshall @rbiswas4 @danielsf @jchiang87 @jbkalmbach 

Please add additional items to help put together our request.  @drphilmarshall and @wmwv will edit and summarize the list and submit through DESC Leadership.

**Comment by cwwalter** [comment] 2016-03-24 19:40
I think this is implicit above but just in case:

Having master builds is good but have a version of sims built against a stable version of the stack when feasible is also useful (preferable) as DM is often changing APIs etc during their development.

**Comment by danielsf** [comment] 2016-03-24 21:14
Just to be clear: the way LSST's continuous integration works, Sims master is already guaranteed to build against DM master.

**Comment by danielsf** [comment] 2016-03-24 21:16
@cwwalter what do you mean by "stable"?  Is a DM weekly release good enough?

**Comment by danielsf** [comment] 2016-03-25 17:44
---
Weekly builds should be tagged for both SIMS and DM.
---
It occurs to me that we may already be able to do this for ourselves (at least for eups distrib install-able versions of the stack).  I just haven't been doing it because I did not realize there was demand for DM stack versions between "official releases" (where "official releases" means things like v11.0 or Winter2016).

The next time I cut a new version of Sims (which will be version 2.2.4), I can just publish a version of lsst_aps that is tagged sims_2_2_4.  The people will have the option of
```
eups distrib install lsst_apps -t sims_2_2_4
```
and getting a version of lsst_apps that is consistent with Sims version 2.2.4 (and so on into the future)

**Comment by wmwv** [comment] 2016-03-25 18:17
@danielsf   Excellent.  That would be great.

**Comment by danielsf** [comment] 2016-03-25 20:44
Follow up to my own post: I ran the idea by Simon and he saw no problem with publishing sims tagged versions of lsst_apps.  So, really, the only thing we can't do for ourselves is guarantee the availability of conda builds with any regularity.

**Comment by drphilmarshall** [comment] 2016-03-25 21:08
At this point, should we pause while we implement the things we can do, and
then send the request for what we know we cannot? If you think that's
sensible, we are only left with what to do about the draft request in the
first comment: I think I'd suggest we edit that so that it reflects our
current understanding, and keep iterating until we are ready to draw
people's attention to this issue thread (at which point the first comment
will be the first thing they see).

**Comment by danielsf** [comment] 2016-03-25 21:47
I am fine with that.  I need to sit down with Mario and talk to him about implementing git-lfs in the conda-lsst build system, anyway.  I will try to broach the subject of who is going to be maintaining conda-lsst long-term when that happens.

**Comment by cwwalter** [comment] 2016-03-28 02:21
> On Mar 24, 2016, at 5:16 PM, danielsf <notifications@github.com> wrote:
> 
> @cwwalter what do you mean by "stable"? Is a DM weekly release good enough?

@danielsf Sorry… missed this before.  

What I meant was that, although having weekly releases is also fine, having a quickly moving sims version that is built against the stable DM version (I mean quarterly releases modulo version that have bugs which must be fixed) is valuable since it gives us a stable API base to build on when we are thinking about the sims work and not DM.

I’m open to be convinced otherwise on this, but having only one thing changing at a time and being able to look at the stable DM documentation is valuable.  I understand that sometimes we will also want to build on a new feature but I think an update to that release might happen in a deliberative fashion.

**Comment by danielsf** [comment] 2016-03-28 16:45
@cwwalter In principle, I agree with you.  I'm not sure if it's possible, though.  For example: sims cannot be built against DM v11.0, which, I think, is still the stable version of record.  Granted, that had to do with changes to afwCameraGeom, which I don't anticipate changing in the near future, but I cannot guarantee that something else we want to change won't come up between stable DM releases.

I think the problem is that Sims is operating on a much more rapid release schedule than DM and, as long as we are trying to maintain a unified LSST software framework, that is occasionally going to involve adding things to the DM stack in service of Sims and requiring us to build against something more modern than the last stable release.

**Comment by rbiswas4** [comment] 2016-03-28 16:46
@cwwalter 
There are two kinds of API changes in the DM stack that you might worry about:

1. Those API that are directly called from sims that may have changed from a release to weekly builds
2. Those API that are only indirectly called by sims or not called at all.

For those in the first category, it would seem that two versions of sims code will need to be produced and maintained, one that corresponds to the stable release, and one that corresponds to weekly builds. I don't think this is done currently, and would probably be a lot of work even apart from creating a build.

For those in the second category, I think this is possible for the user to do this using eups, with different forms of tagging and also in conda using conda environments (for python this corresponds to building a package choosing the versions of different , but this may be a problem if there are static C++ libraries) without requiring a separate build. I have not exactly done this, and it is possible that I am forgetting something (like some problem with libraries). In practice though, I think most changes that we will worry about for which the new build is required will probably be of type 1.

**Comment by rbiswas4** [comment] 2016-03-28 17:09
I  think it would help us prioritize our requests if we kept track of the functionality or use-cases for the requests. This might be in terms of approachability for a casual user, functionality (some need in our workflow, so it could be done in an alternative way if such a method is available) or other categories that I am not thinking of.
 
Approachability: This was supposed to be for 'casual users' of Twinkles. I imagine this is for someone who would want to see what Twinkes is about and to gauge whether they will be interested in getting involved or if they can perhaps use Twinkes code/products for their projects and start off with Twinkles. I think in practice, the set of tasks a 'casual user' can perform will always be a subset of tasks that a more involved user can perform (which is not to say that things cannot or should not be made simpler for everyone). I think we need to define that approximate boundary 

Functionality: Things we need for our setup to absolutely have

For example, in the meeting, when we were talking about conda binaries, I had in mind:
Approachability: for new users to be able to check out Twinkles workings
Functionality Aspects:
- Running on continuous integration systems like travis quickly (eups distrib install takes more than 2 hours to install sims from scratch https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out, but maybe the cacheing can help there too?)
- Practical/Quick ways of getting Twinkles setup running on a cluster

**Comment by cwwalter** [comment] 2016-03-29 02:14
@danielsf Yes, OK I agree.  Clearly we couldn't use V11.0 as you said.   What I meant by "deliberate" above was that I would imagine in those cases we could agree to bump to a  higher version (as opposed to just taking a weekly snapshot) when it became necessary.  But as both you and @rbiswas4 say that is going to be a lot of work and overhead.

**Comment by drphilmarshall** [comment] 2016-08-04 21:59
The request to the project was made, and progress happened!

**Closed by drphilmarshall** 2016-08-04 21:59 UTC
Labels: DM Stack, Epic: Approachability, Framework
