### ISSUE TITLE
processEimage.py ends with runtime error in meas_astrom/matchOptimisticB.py on v488756-fu data

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#219] opened 2016-04-14 22:17 UTC
@jchiang87 You mentioned in our meeting that there was another bug in the Level 2 pipeline, something about the butler being passed something bad. You were going to check with @SimonKrughoff I believe. Here's hoping it's ticketable! We win when we generate DM tickets.

**Comment by jchiang87** [comment] 2016-04-14 22:46
Actually the thing I mentioned to Simon regarding the butler and `obs_lsstSim/ingestImages.py` is pretty minor, just an interface change in some of the pipe task code that is a single line fix in `ingestImages.py`.   But I'm seeing another issue using the merged DM-4302 branch, but I need to understand it better.  The processEimage.py one looks like a genuine bug, along the lines of #161 and #162, but in a different part of the Stack.

**Comment by drphilmarshall** [comment] 2016-04-14 22:50
Ah, OK - feel free to re-title this issue to accurately reflect the problem
you have. I'm still hoping it leads to a DM Ticket! :-)

**Comment by jchiang87** [comment] 2016-04-15 06:14
I've placed the relevant data in `/global/u1/j/jchiang8/twinkles/bugs/issue_219` at NERSC in case anyone wants to reproduce the error.  I'm using the current `tickets/DM-4302` branch of `obs_lsstSim` built against the conda install of lsst_apps which appears to have tag `b2003`.  Here is the command and error message:
```
(my_root)[cori12] processEimage.py input_data --id visit=488756 --output output --doraise --clobber-config

<...skip output...>

processEimage.calibrate.astrometry.matcher: Purged 841 unusable sources, leaving 109 usable sources
Traceback (most recent call last):
  File "/global/u1/j/jchiang8/twinkles/obs_lsstSim/bin/processEimage.py", line 25, in <module>
    ProcessEimageTask.parseAndRun()
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/cmdLineTask.py", line 450, in parseAndRun
    resultList = taskRunner.run(parsedCmd)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/cmdLineTask.py", line 199, in run
    resultList = mapFunc(self, targetList)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/cmdLineTask.py", line 324, in __call__
    result = task.run(dataRef, **kwargs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_tasks/python/lsst/pipe/tasks/processCcd.py", line 171, in run
    icSourceCat = charRes.sourceCat,
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_tasks/python/lsst/pipe/tasks/calibrate.py", line 319, in run
    icSourceCat = icSourceCat,
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_tasks/python/lsst/pipe/tasks/calibrate.py", line 374, in calibrate
    sourceCat = sourceCat,
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/meas_astrom/python/lsst/meas/astrom/astrometry.py", line 198, in run
    res = self.solve(exposure=exposure, sourceCat=sourceCat)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/meas_astrom/python/lsst/meas/astrom/astrometry.py", line 310, in solve
    maxMatchDist = maxMatchDist,
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/meas_astrom/python/lsst/meas/astrom/astrometry.py", line 425, in _matchAndFitWcs
    maxMatchDist = maxMatchDist,
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/pipe_base/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/global/homes/j/jchiang8/.conda/envs/my_root/opt/lsst/meas_astrom/python/lsst/meas/astrom/matchOptimisticB.py", line 330, in matchObjectsToSources
    raise RuntimeError("Unable to match sources")
RuntimeError: Unable to match sources
(my_root)[cori12] 
```

**Comment by SimonKrughoff** [comment] 2016-04-15 17:58
This does not fail for me using 4302 and a stack built at the beginning of the week.  I'm afraid master and the conda have diverged.

**Comment by jchiang87** [comment] 2016-04-15 18:10
yes. everything is in `/nfs/home/jchiang/Twinkles/tickets/issue_219`

**Comment by jchiang87** [comment] 2016-04-15 18:24
I just tried doing `setup lsst_apps -t b2010` at lsst-dev and see the same failure.

**Comment by jchiang87** [comment] 2016-04-15 20:01
Doing
```
$ source /ssd/lsstsw/stack/loadLSST.bash
$ setup lsst_apps
```
as described [here](https://community.lsst.org/t/shared-stack-on-lsst-development-machines/641/15) to get the most recent weekly, I still seeing the same error for that dataset.

**Comment by SimonKrughoff** [comment] 2016-04-15 20:09
@jchiang87 I don't think this is a bug in the stack.  I think it's a bug in the data.  We changed how the inputs were generated at one point.  That required a change in the astrometry data.  If I use a different version of the `and_files` other than the one you included in your package, it works (sort of).

There is a problem with the registry and I'll look into that next.

**Comment by jchiang87** [comment] 2016-04-15 20:12
Are you using the and_files_0229 data, i.e., what is currently being used in the SLAC workflow?

**Comment by SimonKrughoff** [comment] 2016-04-15 20:28
I'm not sure I understand the question.  The and_files_0229 astrometry_net_data files are old and shouldn't be used for anything other than testing with equally old data.  The SLAC workflow is **not** using these files.  It is using an updated set of files.

**Comment by SimonKrughoff** [comment] 2016-04-15 20:32
I'm afraid that I'm going to end up chasing old bugs if we keep testing against old data.  Do you mind running these tests against run1 data instead?

**Comment by jchiang87** [comment] 2016-04-15 20:34
I think we some provenance here.  Where, if any place, do we specify which and_files are being used in the SLAC workflow?  I really have been making a genuine effort to use what I understand to be consistent datasets as well as checking that any changes I make to my local copies of the code actually try to fix things.  If we don't want to waste any more of my time and yours, I think we need to be able to identify those current dataset consistently and easily.

**Comment by SimonKrughoff** [comment] 2016-04-15 20:41
I totally agree.  I don't have any visibility into how the SLAC data are being curated.  This is a problem in general with the astrometry_net_data.  We should eventually be able to ask the butler for the correct data, but that doesn't happen yet.  I'm open to suggestions for how to deal with this in the short term.

**Comment by jchiang87** [comment] 2016-04-15 20:43
>  I don't have any visibility into how the SLAC data are being curated.

How exactly do you know, then, which files the SLAC workflow is using?

**Comment by SimonKrughoff** [comment] 2016-04-15 20:53
I just know what I think I told them to use.

BTW, the ingest bug is fixed on 4302.  How do we close the loop on this so I can merge to master?

**Comment by SimonKrughoff** [comment] 2016-04-15 22:02
@jchiang87 It looks like the SLAC workflow may be using the 0229 and files at: /nfs/farm/g/lsst/u1/users/tonyj/and_files_0229/ (this was on bullet0002).

@tony-johnson can correct me.

**Comment by sethdigel** [comment] 2016-04-15 23:27
The assembleCoadd process of the TwinklesDM task defines an environment variable AND_DIR, which for the runs that Tony made yesterday was indeed set to /nfs/farm/g/lsst/u1/users/tonyj/and_files_0229.  This is in the log files of the runs, e.g., [this one](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/log.jsp?pi=41528845).

**Comment by SimonKrughoff** [comment] 2016-04-15 23:32
Thanks for the pointer @sethdigel

**Comment by jchiang87** [comment] 2016-04-16 01:31
@SimonKrughoff The ingestImages.py script seems to work now.  Thanks.  I've built that branch against the conda dist and verified that I can run the level 2 scripts using that distribution.    If you could start whatever process needs to be done to merge that branch into master that would be great.  I'm going to close this issue.  If any similar bugs arise in the workflow execution, another issue with those specifics can be filed.

**Closed by jchiang87** 2016-04-16 01:31 UTC
Labels: Bug, DM Stack, Epic: Run 1.1

**Comment by SimonKrughoff** [comment] 2016-04-18 16:24
@jchiang87 thanks for all your work on this and for your patience.  I am hoping that the next version of the reference catalogs will really help with the provenance issue we ran into here (it puts a link of the reference catalog in the repository with the data).
