### ISSUE TITLE
Generate unsprinkled instance catalogs for first month of observations for all six bands

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#95] opened 2016-01-19 16:58 UTC
These instance catalogs should include standard variable sources in addition to the usual non-varying stars and galaxies.   They will be used to generate phosim images for testing the Stack analysis in the workflow engine.

**Comment by drphilmarshall** [comment] 2016-01-19 17:10
@wmwv these early data can also be used to test some early light curve /
photometry validation code.

**Comment by wmwv** [comment] 2016-01-19 18:23
Excellent.  I've been working on validation stuff for CFHT and DECam data in https://github.com/lsst/validate_drp
 which should provide a good base to start on.

**Comment by drphilmarshall** [comment] 2016-01-19 21:16
Maybe this and other LSST stack validation code is what we should cover in
our next DM Reading Club? Want to give us a guided tour on Thursday,
Michael?

**Comment by wmwv** [comment] 2016-01-20 14:04
Give me two weeks.  Things are still developing on the LSST as quality check code from HSC is being ported over.  it would be premature to present about this tomorrow.

**Comment by drphilmarshall** [comment] 2016-01-20 15:10
Sounds good, thanks! I think the group is focused on implementation right
now, so the week after next is a good time to reboot the reading group.
I'll ping the thread.

**Comment by jchiang87** [comment] 2016-01-25 21:38
@SimonKrughoff Have you had a chance to work on this?  If you're busy, I can take it on, but I need some instructions on how to include the standard variable sources.   I think we need to get going on generating the phosim images in production mode asap.

**Comment by SimonKrughoff** [comment] 2016-01-25 21:42
@jchiang87 I have looked at it and I'm not finding any variability (I actually meant to add an issue on this today).  Options are:

1. I'm doing something wrong.  Should know later today.
2. It could be a bug in CatSim, then we should help them fix the bug (maybe simulate without variability in the mean time?)
3. It just so happens that there are no variable sources in the catalog in that particular region.  I'd be surprised if this is the case.

I'll post here when I know more.

**Comment by SimonKrughoff** [comment] 2016-01-26 01:21
@jchiang87 @drphilmarshall Here's the story.

Part of the problem is that the area is so small that we just missed examples of several of the variability types.  The M dwarf stars were either not updated in one of the database upgrades or missed in the initial variability model, so don't have variability information.  The result is that only the AGN are variable in this field.

It will take the sims team until next week to get to updating the databases.  The sprinklers are supposed to be done this week.  My suggestion is that we wait to produce variable catalogs until the sprinklers are ready and we can do everything at once.

There are benefits to running non-variable catalogs through and I'm happy to help with that if you think it's worth it.

**Comment by SimonKrughoff** [comment] 2016-02-05 23:07
We've decided to go with sprinkled inputs.  I'm therefore closing this.

**Closed by SimonKrughoff** 2016-02-05 23:07 UTC
Labels: Workflow
