### ISSUE TITLE
Create the DM Level 2 Pipeline for Twinkles

### ISSUE THREAD

**Issue by connolly** [DarkEnergyScienceCollaboration/Twinkles#41] opened 2015-10-27 16:57 UTC
Write the DM tasks and pipeline required for the processing of DM data
- [x] ingest images
- [ ] image subtraction #197 
- [x] source detection
- [x] source measurement
- [x] source matching into objects

**Comment by SimonKrughoff** [comment] 2015-11-10 03:22
Check it out!  Coadded image at the location of the Twinkles field.  This is just 6 epochs and is unsprinkled.  The point was just to get an idea of how to do this so that I can inform the group helping with the workflow.
Single epoch
![image](https://cloud.githubusercontent.com/assets/945715/11053571/055a841e-8717-11e5-98d0-8c79c32d526e.png)
Coadd:
![image](https://cloud.githubusercontent.com/assets/945715/11053590/307967c8-8717-11e5-93c1-f727bc8afe20.png)

**Comment by cwwalter** [comment] 2015-11-10 04:30
👍!

**Comment by drphilmarshall** [comment] 2015-11-10 18:19
Cool! I didn't see any code commits - can you check in the script you  are
working on, please? Nice if your defs and classes can be called
from/imported by a demo notebook too, so we can all see what's going on
(and join in the development work). The current design is to put everything
in the `twinkles` folder, so that we can `import twinkles`. Thanks!

**Comment by SimonKrughoff** [comment] 2015-11-10 18:36
Yes, of course.  Part of the problem is that most of the actual code is going in the obs_lsstSim package, since part of this process is to fix actual bugs in that package.  I'll make sure I at least get some sort of cookbook to this point checked in today.

**Comment by drphilmarshall** [comment] 2015-11-10 18:59
Great, thanks! Regarding your cookbook: it's going to soon become quite
important to enable any of us to git pull in Twinkles and *just run* the
code to make and analyze images. The CI group are going to want scripts
that they can farm out, and SN and SL groups will want to run small scale
experiments of their own as they work out their science tests - so a set of
demos will be very helpful indeed.

Would be good to find you a willing test engineer to keep up with you, and
make sure the demos run? I'm happy to try and do some of this on my laptop,
maybe Tom (at SLAC) and Bryce (at UW) could as well? It sounds like part of
the demo will be to help the user update their local stack to reflect the
changes to obs_lsstSim that you are making.

**Comment by SimonKrughoff** [comment] 2015-11-11 04:21
I've added a start at a cookbook in /code.  We can move it around as I get a chance to flesh it out.

**Comment by drphilmarshall** [comment] 2015-11-11 18:32
That's great, thanks @SimonKrughoff ! I am reading your cookbook at https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/twinkles_cookbook.md  You are calling a lot of scripts - are they PhoSim scripts? They don't seem to be DM or Sims scripts (at least, they are not on my stack-defined PATH). If they are new, would you mind checking them in please? And if not, explaining where they live? 

This markdown file is not many edits away from becoming a well-documented shell script. It seems to me that that would be a better format to keep these notes in than a markdown file (I don't want to have to paste commands into a terminal line by line!) Workflow people @tony-johnson @TomGlanzman @richardxdubois : what should we do to Simon's cookbook to enable you to reproduce his image creation in the workflow engine?
 
Simon, I note that most of what is being called is python. Does this mean that we really should be writing python pipeline scripts that call the classes and functions being used in the lower level scripts? It's hard to tell without seeing the scripts themselves. Interested to hear what you all think!

**Comment by SimonKrughoff** [comment] 2015-11-11 18:50
The only script that I'm calling in that cookbook that is not in the stack is [generatePhosimInput.py](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/generatePhosimInput.py).  The rest of the scripts are in either obs_lsstSim or pipe_tasks (I have left out any mention of how I ran phosim).  They should be on your path if you have those packages setup.

Regarding the chaining of the scripts, in the lexicon of the LSST stack, these are all pipe_tasks and are made to be chained together, if that makes sense.  I'm calling these individually because they represent logical blocks of processing: calibration, warping, coaddition.  Each of those scripts could be a box in a workflow.

I do wonder how useful having these in a shell script is because I find that I run some of the steps once (calibration) and then run other steps multiple times until I converge on a config that works, but if you want a script that can run through a predefined set of data, I'm happy to make that happen.

**Comment by drphilmarshall** [comment] 2015-11-11 19:21
I see - you are describing the process of assembling an astronomical
processing pipeline ("I run some of the steps once (calibration) and then
run other steps multiple times until I converge on a config that works"). I
guess when I've done this in the past I've been working on the superscript
 that runs that pipeline all the way through (partly because it typically
has to be done multiple times early on, and partly because I want a record
of what I have done that can be re-ran very straightforwardly). In the
Twinkles case I guess things are a bit different: we are planning on having
some sort of workflow engine run these scripts. I guess once we see the
workflow code that calls these scripts it'll be clearer how things are
going to work. I'll go read about the Hack Day progress :-)

**Comment by SimonKrughoff** [comment] 2015-11-11 23:29
I've updated the cookbook.  We have all the pieces in place to get lightcurves, but not difference images yet.  I'll have to figure out how to do that for SNe.

**Comment by drphilmarshall** [comment] 2015-11-13 23:56
You are so close, @SimonKrughoff ! But @wmwv only awards cigars for DIASource fpFluxes, I believe.

**Comment by SimonKrughoff** [comment] 2015-11-14 00:32
That's close.  I made some difference images, but they were unusable because the template was not psf matched (I think).  I'll work on a pipeline to make psf matched coadds so we can get decent DIASources.

**Comment by SimonKrughoff** [comment] 2015-11-20 22:13
I haven't done any more processing, but I did do a simple sanity check that our processing isn't producing total garbage.  To make the following plots I:
1. Coadded 9 visits
2. Detected on the coadd
3. Force photometered on the individual single visit images.
4. Selected lightcurves for point-like sources in the coadd that have 9 observations (are in all epochs).
5. For each lightcurve I plot the fractional scatter as a function of calibrated magnitude.
![image](https://cloud.githubusercontent.com/assets/945715/11313296/a85c7d4e-8f90-11e5-8101-9c40b5fb73f7.png)
![image](https://cloud.githubusercontent.com/assets/945715/11313311/c4fb9b60-8f90-11e5-8904-c25230e0d8ea.png)
In this dataset we are getting repeatability of ~2%

**Comment by drphilmarshall** [comment] 2015-11-21 19:50
Nice! :-)

I see you get a noise to signal ratio of about 0.2 at 24.5 or so, which is
indeed supposed to be the 5-sigma point source limit - so I guess the
background part of the noise is about right. At what source brightness do
we become source limited? How many counts do we expect from a 19th mag
source? It would be cool to overlay a theory curve on this plot. Another
way of saying this: what sets the 2% reliability level? Are these objects
non-variable stars?

**Comment by drphilmarshall** [comment] 2015-12-09 20:16
I just noticed that @SimonKrughoff overlaid a nice theory line on top of his cookbook fpFluxes :-) I take it that these are indeed non-variable stars, and that the source of the 2% reliability floor is unknown. Let's keep tracking this quantity as we proceed (including comparing with the Reprocessors) - in the first instance I guess having the workflow engine make this plot is a good idea, that Tony is working on. In the meantime, I think it's fair to say that we have a working Twinkles DM pipeline! :-)

![Simon's cookbook output plot](https://raw.githubusercontent.com/DarkEnergyScienceCollaboration/Twinkles/master/code/repeat.png)

**Comment by SimonKrughoff** [comment] 2015-12-09 21:03
@drphilmarshall What you say is correct.  I haven't tracked down the cause of the systematic floor at 2%, and these measurements are for non-variable point sources.  One caveat is that I believe I simulated these with cloud obscuration turned on.  I will try this again with that turned off.

**Comment by drphilmarshall** [comment] 2016-03-24 00:20
@connolly you are right to re-open this: DIASources or bust! :-)

**Comment by tony-johnson** [comment] 2016-07-12 14:25
Done except for image differencing, which is being tracked under a separate issue #197. Closing this issue since Run 2 is now complete.

**Closed by tony-johnson** 2016-07-12 14:25 UTC
Labels: DM Stack, Epic, Epic: DM Level 2 Pipeline, Framework

**Comment by drphilmarshall** [comment] 2016-07-12 14:39
Excellent!
